# <center>Тема 2. Углубленные приемы pandas, collections, numpy</center>
## <center>Практическое задание. Работа с векторами в библиотеке NumPy</center>

In [5]:
import numpy as np
import pandas as pd

**1. Создайте numpy массив с числами от 100 с шагом в 10, размера 10х5**

In [6]:
# Ваш код здесь

In [7]:
np.arange(100, 600, 10).reshape((10, 5))

array([[100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240],
       [250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490],
       [500, 510, 520, 530, 540],
       [550, 560, 570, 580, 590]])

**2. Создайте numpy массив с числами от 100 с шагом в 10, размера 10х5 заполеннный змейкой**  
---------->  
<---------  
---------->  

In [8]:
a = np.arange(100, 600, 10).reshape((10, 5))
a[1::2] = a[1::2, ::-1]
a

array([[100, 110, 120, 130, 140],
       [190, 180, 170, 160, 150],
       [200, 210, 220, 230, 240],
       [290, 280, 270, 260, 250],
       [300, 310, 320, 330, 340],
       [390, 380, 370, 360, 350],
       [400, 410, 420, 430, 440],
       [490, 480, 470, 460, 450],
       [500, 510, 520, 530, 540],
       [590, 580, 570, 560, 550]])

**3. Вычтите из каждого ряда первого массива соответствующее значение из второго**  
Result
array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [9]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [10]:
# Ваш код здесь

In [15]:
a_2d.T - b_1d

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [16]:
a_2d - b_1d[:, None]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [17]:
a_2d - b_1d.reshape(1, 3, 1)

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

**4. Заменить все положительные числа массива на 1, отрицательные на 0**

In [18]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=(3000,3000))

In [19]:
# Ваш код здесь

In [20]:
X

array([[-316, -441,  653, ...,  773,  961, -475],
       [-187,  456, -432, ...,  168,  273, -169],
       [ 936,  475, -128, ...,  408, -892, -310],
       ...,
       [-921,  396,  457, ...,  646, -450, -387],
       [ 645,  943, -435, ...,  863, -920,  790],
       [ 641, -548,  379, ...,  347,  -67, -352]])

In [21]:
np.ones(X.shape) * (X > 0)

array([[0., 0., 1., ..., 1., 1., 0.],
       [0., 1., 0., ..., 1., 1., 0.],
       [1., 1., 0., ..., 1., 0., 0.],
       ...,
       [0., 1., 1., ..., 1., 0., 0.],
       [1., 1., 0., ..., 1., 0., 1.],
       [1., 0., 1., ..., 1., 0., 0.]])

**5. Создать numpy массив нулей размера NхM c границей из единиц, шириной K**

In [22]:
N = 10
M = 6
K = 2

In [23]:
# Ваш код здесь

In [24]:
a = np.ones((N, M))
a[K:N-K, K:M-K] = 0
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 1., 1.],
       [1., 1., 0., 0., 1., 1.],
       [1., 1., 0., 0., 1., 1.],
       [1., 1., 0., 0., 1., 1.],
       [1., 1., 0., 0., 1., 1.],
       [1., 1., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

**6. Вывести все name и среднее число заказов типа 2 по месяцам, для которых общая сумма заказов за месяц, в которых число заказов типа 1 больше числа заказов типа 2, превышает среднюю сумму заказов по всем месяцам.**  
Дополнительно: не использовать присваивание

In [25]:
# не менять
np.random.seed(17)
data = pd.DataFrame({'name': np.random.randint(0, 10, size=1000),
                     'date': pd.date_range('2019-01-01', '2020-01-01', periods=1000),
                     'order_type_1': np.random.randint(0, 100, size=1000),
                     'order_type_2': np.random.randint(0, 100, size=1000)})
data.loc[data['order_type_1'] % 5 == 0, 'order_type_1'] = np.nan
data.loc[data['order_type_2'] % 3 == 0, 'order_type_2'] = np.nan
data.head()

# order_type - сумма заказа типа 1 и типа 2 на определенную дату. NaN если заказа не было

name                          date  order_type_1  order_type_2
0     1 2019-01-01 00:00:00.000000000           9.0          61.0
1     6 2019-01-01 08:46:07.567567567          47.0           NaN
2     6 2019-01-01 17:32:15.135135135          54.0           NaN
3     9 2019-01-02 02:18:22.702702702          83.0           NaN
4     0 2019-01-02 11:04:30.270270270          18.0           NaN

In [26]:
# Ваш код здесь

In [28]:
for n, ndf in (data.groupby(['name', pd.Grouper(freq='M', key='date', closed='right')])
                   .agg({'order_type_1': ['sum', 'count'], 'order_type_2': 'count'})
                   .groupby('name')):
    print(n, (ndf[(ndf['order_type_1', 'count'] > ndf['order_type_2', 'count']) & 
                  (ndf['order_type_1', 'sum'] > ndf['order_type_1', 'sum']
                   .mean())])['order_type_2', 'count'].mean())

0 6.6
1 5.333333333333333
2 5.833333333333333
3 5.75
4 6.4
5 5.75
6 6.4
7 5.666666666666667
8 6.0
9 4.6
